/**
 * MARGINAL-BYTE DECOMPOSITION
 * ===========================
 *
 * `bench/size/probe.ts` reports ~5,170 B per "node() site" from its
 * `node-scaling` group. But that group's generator (probe.ts:95-108) adds, per
 * increment, a WHOLE RULE:
 *
 *   N{i}: node('N{i}', sequence(regex(/[a-z]+/), literal('x'), optional(literal(';'))), build)
 *
 * ...and ALSO appends `g.N{i}` as another arm of the Root `choice(...)`.
 *
 * So the headline number is bytes per (node preamble + 3-term sequence + regex +
 * 2 literals + optional + one more choice arm), not bytes per node() preamble.
 * A hot/cold split can only attack the node preamble, so before building one we
 * need to know what fraction that actually is.
 *
 * METHOD: same-shape variants, differing in exactly one construct, each measured
 * at two sizes. The MARGINAL cost (bytes(hi) - bytes(lo)) / (hi - lo) cancels the
 * fixed module preamble, which is what makes these attributable.
 */
import { loadLowerer, measure, type Unit } from './probe.ts'

const MACRO = `import { rules, node, sequence, choice, many, literal, regex, optional } from 'parseman' with { type: 'macro' }`

type Gen = (n: number) => string

/** As probe.ts nodeScale: node + sequence(regex, literal, optional(literal)) + choice arm. */
const full: Gen = (n) => mod(n, (i) =>
  `  N${i}: node('N${i}', sequence(regex(/[a-z]+/), literal('${ch(i)}'), optional(literal(';'))), (c) => ({ t: 'N${i}', c })),`)

/** Identical body, NO node() wrapper. Delta vs `full` = the node() preamble. */
const noNode: Gen = (n) => mod(n, (i) =>
  `  N${i}: sequence(regex(/[a-z]+/), literal('${ch(i)}'), optional(literal(';'))),`)

/** node() around a bare regex. Delta vs `noNodeBare` = node preamble on a minimal body. */
const bare: Gen = (n) => mod(n, (i) =>
  `  N${i}: node('N${i}', regex(/[a-z]+/), (c) => ({ t: 'N${i}', c })),`)

const noNodeBare: Gen = (n) => mod(n, (i) =>
  `  N${i}: regex(/[a-z]+/),`)

/** Structural node (no build reducer) around a bare regex. */
const structural: Gen = (n) => mod(n, (i) =>
  `  N${i}: node('N${i}', regex(/[a-z]+/)),`)

function ch(i: number): string { return String.fromCharCode(97 + (i % 26)) }

function mod(n: number, def: (i: number) => string): string {
  const defs: string[] = []
  for (let i = 0; i < n; i++) defs.push(def(i))
  defs.push(`  Root: node('Root', many(choice(${Array.from({ length: n }, (_, i) => `g.N${i}`).join(', ')})), (c) => ({ t: 'Root', c })),`)
  return `${MACRO}\nexport const g = rules((g) => ({\n${defs.join('\n')}\n}))\n`
}

const VARIANTS: Record<string, Gen> = { full, noNode, bare, noNodeBare, structural }
const SIZES = [4, 8, 16, 32]

const lower = await loadLowerer()
const results: Record<string, Record<number, number>> = {}

for (const [name, gen] of Object.entries(VARIANTS)) {
  results[name] = {}
  for (const n of SIZES) {
    const src = gen(n)
    // `nodes` is only used for the probe's bytesPerNode; force 1 so units with
    // zero node() sites (noNode*) do not trip its zero-node guard.
    const u: Unit = { id: `dec-${name}-${n}`, group: 'decompose', floor: '0.14.0', nodes: 1, files: { 'g.ts': src }, entry: 'g.ts' }
    results[name]![n] = measure(u, lower).genBytes
  }
}

const marginal = (name: string): number =>
  (results[name]![32]! - results[name]![8]!) / 24

console.log('\nGENERATED BYTES')
console.log('variant'.padEnd(14) + SIZES.map((n) => `n=${n}`.padStart(10)).join('') + '   marginal B/site (32-8)/24')
for (const name of Object.keys(VARIANTS)) {
  console.log(name.padEnd(14) + SIZES.map((n) => String(results[name]![n]).padStart(10)).join('') + '   ' + marginal(name).toFixed(0).padStart(8))
}

console.log('\nATTRIBUTION (marginal B per added rule)')
const mFull = marginal('full'), mNoNode = marginal('noNode')
const mBare = marginal('bare'), mNoNodeBare = marginal('noNodeBare'), mStruct = marginal('structural')
console.log(`  full rule (probe's "per node site")        ${mFull.toFixed(0)}`)
console.log(`  same rule WITHOUT node()                   ${mNoNode.toFixed(0)}`)
console.log(`  => node() preamble on a seq body           ${(mFull - mNoNode).toFixed(0)}  (${(100 * (mFull - mNoNode) / mFull).toFixed(1)}% of headline)`)
console.log(`  => body + choice arm (NOT node's to fix)   ${mNoNode.toFixed(0)}  (${(100 * mNoNode / mFull).toFixed(1)}%)`)
console.log(`  node(regex) minimal body                   ${mBare.toFixed(0)}`)
console.log(`  bare regex, no node()                      ${mNoNodeBare.toFixed(0)}`)
console.log(`  => node() preamble on a minimal body       ${(mBare - mNoNodeBare).toFixed(0)}`)
console.log(`  structural node(regex) (no build)          ${mStruct.toFixed(0)}`)
console.log(`  => structural preamble                     ${(mStruct - mNoNodeBare).toFixed(0)}`)

console.log('\n10x-TARGET IMPLICATION')
console.log(`  If a hot/cold split made the node preamble FREE for every cold node,`)
console.log(`  the probe's per-site cost would fall ${mFull.toFixed(0)} -> ${mNoNode.toFixed(0)} B,`)
console.log(`  a ${(100 * (mFull - mNoNode) / mFull).toFixed(1)}% cut. Target needs ~1,170 B/site.`)
console.log(`  Reachable by zeroing the node preamble alone? ${mNoNode <= 1170 ? 'YES' : 'NO'}`)
