/**
 * HOT/COLD TRADEOFF CURVE
 * =======================
 *
 * Sweeps the capture-restore sharing threshold (`CR_SHARE_MIN` in
 * src/compiler/codegen.ts) and reports generated size at each setting, per
 * fixture. `Infinity` is the all-inline 0.45 behaviour and is the baseline.
 *
 * The threshold is overridden through the environment rather than a parameter
 * because it is read at Ctx construction in several places; a single env read
 * keeps the sweep honest (one code path, one constant) instead of adding a
 * plumbing option that only the benchmark would ever set.
 */
import { join } from 'node:path'
import { gzipSync } from 'node:zlib'
import { execFileSync } from 'node:child_process'

const HERE = import.meta.dirname
const THRESHOLDS = ['Infinity', '400', '300', '250', '200', '150', '100', '0']

if (process.env.PM_CR_CHILD === '1') {
  const { compile } = (await import(join(HERE, '..', '..', 'src', 'index.ts'))) as { compile: (c: unknown) => { source: string } }
  const SPECS = [
    ['example/json', '../../examples/json/parser.ts', 'jsonDoc'],
    ['example/csv', '../../examples/csv/parser.ts', 'csvParser'],
    ['example/graphql', '../../examples/graphql/parser.ts', 'graphqlDoc'],
    ['example/css', '../../examples/css/parser.ts', 'Stylesheet'],
    ['example/lang', '../../examples/lang/parser.ts', 'exprParser'],
    ['example/jsonc', '../../examples/json/jsonc.ts', 'jsoncValue'],
    ['example/jsonl', '../../examples/json/jsonl.ts', 'jsonl'],
  ] as const
  const out: Record<string, [number, number]> = {}
  for (const [id, mod, name] of SPECS) {
    const m = (await import(join(HERE, mod))) as Record<string, unknown>
    const gen = compile(m[name]).source
    out[id] = [Buffer.byteLength(gen), gzipSync(gen).length]
  }
  process.stdout.write('@@' + JSON.stringify(out) + '@@')
  process.exit(0)
}

const rows: Record<string, Record<string, [number, number]>> = {}
for (const t of THRESHOLDS) {
  const raw = execFileSync(process.execPath, ['--import', 'tsx/esm', join(HERE, 'hotcold-curve.ts')], {
    env: { ...process.env, PM_CR_CHILD: '1', PM_CR_SHARE_MIN: t },
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })
  const m = /@@([\s\S]*)@@/.exec(raw)
  if (!m) throw new Error(`threshold ${t}: child produced no result\n${raw.slice(0, 500)}`)
  rows[t] = JSON.parse(m[1]!)
}

const ids = Object.keys(rows.Infinity!)
const base = rows.Infinity!

console.log('\nGENERATED BYTES vs CR_SHARE_MIN  (Infinity = 0.45 all-inline baseline)')
console.log('  ' + 'fixture'.padEnd(18) + THRESHOLDS.map(t => t.padStart(10)).join(''))
for (const id of ids) {
  console.log('  ' + id.padEnd(18) + THRESHOLDS.map(t => String(rows[t]![id]![0]).padStart(10)).join(''))
}
const tot = (t: string) => ids.reduce((s, id) => s + rows[t]![id]![0], 0)
console.log('  ' + 'TOTAL'.padEnd(18) + THRESHOLDS.map(t => String(tot(t)).padStart(10)).join(''))
console.log('  ' + 'vs baseline'.padEnd(18) + THRESHOLDS.map(t => (100 * (tot(t) - tot('Infinity')) / tot('Infinity')).toFixed(2).padStart(10)).join(''))

console.log('\nPER-FIXTURE % CHANGE AT EACH THRESHOLD')
console.log('  ' + 'fixture'.padEnd(18) + THRESHOLDS.map(t => t.padStart(10)).join(''))
for (const id of ids) {
  const b = base[id]![0]
  console.log('  ' + id.padEnd(18) + THRESHOLDS.map(t => (100 * (rows[t]![id]![0] - b) / b).toFixed(2).padStart(10)).join(''))
}

console.log('\nGZIP TOTAL')
const gz = (t: string) => ids.reduce((s, id) => s + rows[t]![id]![1], 0)
console.log('  ' + 'gzip'.padEnd(18) + THRESHOLDS.map(t => String(gz(t)).padStart(10)).join(''))
console.log('  ' + 'vs baseline'.padEnd(18) + THRESHOLDS.map(t => (100 * (gz(t) - gz('Infinity')) / gz('Infinity')).toFixed(2).padStart(10)).join(''))
