// AUTO-GENERATED by scripts/gen-favicons.mjs — do not edit.
// Regenerate with: pnpm docs:favicons
import type { HeadConfig } from 'vitepress'

export const faviconHead: HeadConfig[] = [
  [
    "link",
    {
      "rel": "icon",
      "type": "image/x-icon",
      "href": "/parseman/favicon.ico"
    }
  ],
  [
    "link",
    {
      "rel": "icon",
      "type": "image/png",
      "sizes": "16x16",
      "href": "/parseman/favicon-16x16.png"
    }
  ],
  [
    "link",
    {
      "rel": "icon",
      "type": "image/png",
      "sizes": "32x32",
      "href": "/parseman/favicon-32x32.png"
    }
  ],
  [
    "link",
    {
      "rel": "apple-touch-icon",
      "sizes": "180x180",
      "href": "/parseman/apple-touch-icon-180x180.png"
    }
  ],
  [
    "meta",
    {
      "name": "theme-color",
      "content": "#ce2b37"
    }
  ]
]
