/**
 * Generate the railroad-diagram examples for the docs. Produces two artifacts:
 *
 *   docs/guide/_railroad-example.md   — one small inline SVG (the `Array` rule),
 *                                       pulled into the guide via <!--@include-->.
 *   docs/public/railroad-example.html — the FULL multi-rule page (toRailroadHtml),
 *                                       served as a static asset and linked to.
 *
 * Regenerate after changing the example grammar or bumping the vendored diagram
 * library:
 *
 *   node --import tsx/esm scripts/gen-railroad-svg.ts
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { rules, sequence, choice, literal, regex, optional, sepBy, type Combinator } from '../src/index.ts'
import { toRailroadSvg, toRailroadHtml, RAILROAD_CSS } from '../src/spec/index.ts'

// A small JSON grammar — enough to show a sequence, an optional, a separated
// repetition (the loop), a choice, and cross-rule references.
const grammar = rules(self => ({
  Value: choice(self.Object as Combinator<unknown>, self.Array as Combinator<unknown>, regex(/"[^"]*"/), regex(/-?[0-9]+/), literal('true'), literal('false'), literal('null')),
  Object: sequence(literal('{'), optional(sepBy(self.Member as Combinator<unknown>, literal(','))), literal('}')),
  Member: sequence(regex(/"[^"]*"/), literal(':'), self.Value as Combinator<unknown>),
  Array: sequence(literal('['), optional(sepBy(self.Value as Combinator<unknown>, literal(','))), literal(']')),
}))

const regexDisplay = (src: string): string => (src.startsWith('"') ? 'string' : 'number')

// ── Inline: one small diagram (the Array rule) ──────────────────────────────
const array = toRailroadSvg(grammar, { regexDisplay }).find((s) => s.name === 'Array')!

// Scope the vendored diagram CSS under our wrapper so it can't leak into the rest
// of the docs page, and drop terminal text to 13px (the lib sizes boxes for ~8px
// glyphs; its own 14px-bold advances wider and crowds the edges).
const scopedCss = RAILROAD_CSS.replace(/^svg\.railroad-diagram/gm, '.railroad-embed svg.railroad-diagram')
  + '\n.railroad-embed svg.railroad-diagram text { font-size: 13px; }'

const block = `<!-- GENERATED by scripts/gen-railroad-svg.ts — do not edit by hand. -->
<style scoped>
${scopedCss}
.railroad-embed { margin: 1rem 0; }
.railroad-embed figcaption { font-size: 0.8rem; color: var(--vp-c-text-2); margin-bottom: 0.35rem; }
.railroad-embed .railroad-scroll { overflow-x: auto; border-radius: 8px; }
.railroad-embed svg.railroad-diagram { display: block; }
</style>

<figure class="railroad-embed">
  <figcaption><code>${array.name}</code></figcaption>
  <div class="railroad-scroll">${array.svg}</div>
</figure>
`

const partial = fileURLToPath(new URL('../docs/guide/_railroad-example.md', import.meta.url))
writeFileSync(partial, block)

// ── Full page: every rule, as a standalone linkable asset ───────────────────
const fullHtml = toRailroadHtml(grammar, { title: 'JSON — syntax diagrams', regexDisplay })
const full = fileURLToPath(new URL('../docs/public/railroad-example.html', import.meta.url))
writeFileSync(full, fullHtml)

// eslint-disable-next-line no-console
console.log(`wrote ${partial} (${block.length} B, inline Array) and ${full} (${fullHtml.length} B, full page)`)
